language: rust
rust:
    - stable
    - beta
    - nightly
matrix:
    allow_failures:
        - rust: nightly
before_install:
    - ci/install-laszip.sh $HOME/local
    - export CPATH=$HOME/local/include
    - export LIBRARY_PATH=$HOME/local/lib
    - export LD_LIBRARY_PATH=$HOME/local/lib
